### ISSUE TITLE
Import wildcard

### ISSUE THREAD

**Issue by OttoRobba** [leafo/moonscript#231] opened 2016-01-07 02:11 UTC
This could be quite nifty so we can easily localize an entire module. Even if said module got modified and updated, it would still be properly imported. Quite useful for creating libraries.

```moonscript
--Suppose a module 'additions' containing four functions. add, add1, add2, add3.
import * from additions

--same as
import add, add1, add2, add3 from additions
```

**Comment by Kingdaro** [comment] 2016-01-07 02:29
Originally, I thought this wasn't quite able to be implemented _cleanly_, but I believe this _can_ be done through _ENV (lua 5.2+ only):
```lua
local env = _ENV
do
  local from = additions
  for k,v in pairs(from) do
    env[k] = v
  end
end

add(1, 2)
```

Even still, I don't really support, as polluting the local namespace with dependencies the script's not even using is a pretty bad idea, I think.

**Comment by OttoRobba** [comment] 2016-01-07 02:32
It would great improve the experience of using helper functions like map, each, filter, etc...

```moonscript
import map, each, select, reject, invoke, pluck, reduce, max, min, detect, all, any, sort, reverse from require "underscore"

**Comment by leafo** [comment] 2016-01-07 02:58
Duplicate of #59

The implementation is not trivial, since the exported function is typically only known at run time, but locals must be created at compile time.

**Comment by leafo** [comment] 2016-01-07 07:02
Also knowing imports at compile time lets you use a linter.

**Comment by leafo** [comment] 2016-09-26 00:19
Going to close this, since there's no way to create the locals at compile time without executing the module. If you want to inject stuff into the environment then I recommend writing a function to do it.

**Closed by leafo** 2016-09-26 00:19 UTC
